apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: gitlab
  name: gitlab
spec:
  type: NodePort
  ports:
  - name: "80"
    port: 80
    nodePort: 30080
  - name: "443"
    port: 443
    nodePort: 30443
  - name: "22"
    port: 22
    nodePort: 30022
  selector:
    io.kompose.service: gitlab
status:
  loadBalancer: {}
