# PV for /var/log/gitlab folder
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv1
spec:
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nfs/logs
    server: 10.100.8.51
    readOnly: false

---

# Volume claim for the /var/log/gitlab folder
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc1
spec:
  accessModes:
  - ReadWriteMany      
  resources:
     requests:
       storage: 40Gi    
